# Theme
remote_theme                : "mmistakes/minimal-mistakes"
minimal_mistakes_skin       : "air"

# Site Settings
title                       : "College Recipes"
name                        : "Aliya"
description                 : "(cool kids only)"


# Reading Files
include:
    - .htaccess
    - _pages

# Collections
collections:
    sweet:
        output: true
        permalink: /:collection/:path/
    savory:
        output: true
        permalink: /:collection/:path/
    basic:
        output: true
        permalink: /:collection/:path/


# category_archive:
#     type: liquid
#     path: /categories/
# tag_archive:
#     type: liquid
#     path: /tags/