# Theme
remote_theme                : "mmistakes/minimal-mistakes"
minimal_mistakes_skin       : "air"

# Site Settings
title                       : "College Recipes"
name                        : "Aliya"
description                 : "(cool kids only)"


